### ISSUE TITLE
Hotkeys not working

### ISSUE THREAD

**Issue by 2relativ** [RobLoach/libretro-dolphin-launcher#23]
Hello,

first let me tell you that this a great piece of work. Somehow the dolphin core keeps crashing and the verbose mode doesn't list anything! Anyway. I was looking for an alternative and found this. But somehow neither the hotkeys I defined in dolphin nor in Retroarch work! That is quite irritating if you want to close a game via gamepad. This way only Alt+F4 works.
I am using Ubuntu Mate. Tested on Retroarch 1.7.9, 1.8.0 and 1.8.1

**Comment by RobLoach** [comment]
Sounds like an issue for Dolphin. This is just about launching it. Just tested the escape key as a hotkey and it seems to be working here.

I'm on Ubuntu MATE 18.10. Did find I had to save a hotkey profile to ensure it was loading okay.

**Comment by 2relativ** [comment]
Yeah, but that is the crazy part. In Dolphin directly the hotkeys work. But if I launch it from Retroarch...
