### ISSUE TITLE
[Request] Dolphin without it's GUI

### ISSUE THREAD

**Issue by CoalaJoe** [RobLoach/libretro-dolphin-launcher#7]
Hey @RobLoach 
Just found that:
![image](https://cloud.githubusercontent.com/assets/5689499/22591680/11d55b84-ea16-11e6-9dab-d9d50787007e.png)
I am not sure you know that, but I think this could add really to the experience.

**Comment by RobLoach** [comment]
Oh! Fancy... So when there is a game, run dolphin-emu-nogui with -e, without use dolphin-emu.

**Comment by CoalaJoe** [comment]
Yeah. Works pretty good, and you don't have to accept the dolphin prompt when exiting.

**Comment by RobLoach** [comment]
Dolphin 4 doesn't have this. We should try dolphin-emu-nogui, and gracefully fallback to dolphin-emu.

**Comment by CoalaJoe** [comment]
Jep.

**Comment by RobLoach** [comment]
Tried the following, wasn't really working that well:

``` c
/**
 * libretro callback; Called when a game is to be loaded.
 */
bool retro_load_game(const struct retro_game_info *info)
{
   // TODO: Find where "dolphin-emu" lives.

   // Launch without the gui if available (Dolphin 5).
   char command[512] = "dolphin-emu-nogui";

   // Check if there is content to load.
   if (info != NULL && info->path != NULL && info->path[0] != '\0') {
      sprintf(command, "%s --exec=\"%s\"", command, info->path);
   }

   // Check if running Dolphin works.
   if (system(command)) {
      printf("Returned true on dolphin-emu-nogui");
      return true;
   }
   //log_cb(RETRO_LOG_INFO, "fasdfadsfda");
   printf("Fallback to dolphin-emu");

   // Dolphin 4 does not have dolphin-emu.
   strcpy(command, "dolphin-emu");
   if (info != NULL && info->path != NULL && info->path[0] != '\0') {
      // Execute with --batch.
      sprintf(command, "%s --batch --exec=\"%s\"", command, info->path);
   }

   return system(command) != -1;
}
```

Looks like while the command is not found, it still returns a valid execution.

**Comment by CoalaJoe** [comment]
On what version of Dolphin did you try that?

**Comment by RobLoach** [comment]
Dolphin 4... Was as getting the following:

```
sh: command dolphin-emu-nogui not found
Returned true on dolphin-emu-nogui
```

Seems like `system()` returns true when the command is not found. May need a cleaner wrapper for executing an external application.

**Comment by CoalaJoe** [comment]
The easiest thing would be running this command `dolphin-emu-nogui --version` and see if it returns "Dolphin 5.0". Maybe with RegEx?

**Comment by RobLoach** [comment]
@CoalaJoe Fixed it. Was checking for the wrong return value from `system()`. Thanks a lot for finding this one! Great feature.

Mind testing it out?

**Comment by CoalaJoe** [comment]
Sure! But my PC currently has no GPU. I'll try it as soon as i can.
